## verifica o tipo de dado de uma string
text = input('Digite um texto')
print('O tipo primitivo dess valor:', type(text))
print('Só tem espaço:', text.isspace())
print('É um numero:', text.isnumeric())
print('É alfabeético:', text.isalpha())
print('É alfanumérico:', text.isalnum())
print('Está em maiúsculo:', text.isupper())
print('Está em minusculo:', text.islower())
print('Está capitalizado:', text.istitle())