#### APPLICATION GLPI
#### Autor   : Rafael Tadeu Lima Almeida
#### Contato : rafaeltadeu01@hotmail.com

version: '3.3'
services: 
   mysql-glpi:
    image: mysql:5.7.23
    container_name: srv-db-glpi
    labels:
       conteiner.description: "Server DataBase MySQL5.7 FOR GLPI"
    hostname: srv-db-glpi
    restart: always
    ports:
       - "3306:3306"
    volumes:
       - ./storage/mysq-glpi/var/lib/mysql:/var/lib/mysql
    env_file:
       - ./mysql-glpi.env

   glpi:
    image: diouxx/glpi
    container_name : srv-glpi
    labels:
       conteiner.description: "Application GLPI"
    hostname: srv-glpi
    restart: always
    ports:
       - "80:80"
    volumes:
       - ./storage/glpi/:/var/www/html/glpi
    env_file:
       - ./glpi.env
    depends_on:
       - mysql-glpi
    links :
       - mysql-glpi